export const palette = {
  black: "#1d1d1d",
  white: "#ffffff",
  offWhite: "#e6e6e6",
  orange: "#FBA928",
  orangeDarker: "#EB9918",
  lightGrey: "#939AA4",
  lighterGrey: "#CDD4DA",
  angry: "#dd3333",
  prettyPink: "#FF2D55",
  babyPink: "#FF829A",
  lightPink: "#FFBFCB",
  lighterPink: "#FFD5DD",
  pinkGray: "#d8cdd5",
}
